package guide

// GitEntries is the full list of git guide items.
var GitEntries = []Entry{
	{
		Name:     "git init",
		Cmd:      "git init — initialize repository",
		Desc:     "Create a new Git repository in the current directory",
		Category: "Getting Started",
		CastFile: "git-init.cast",
	},
	{
		Name:     "git status",
		Cmd:      "git status — check state",
		Desc:     "Show which files are staged, modified, or untracked",
		Category: "Getting Started",
		CastFile: "git-status.cast",
	},
	{
		Name:     "git add",
		Cmd:      "git add — stage changes",
		Desc:     "Stage files to be included in the next commit",
		Category: "Daily Workflow",
		CastFile: "git-add.cast",
	},
	{
		Name:     "git commit",
		Cmd:      "git commit — save snapshot",
		Desc:     "Record staged changes as a new commit with a message",
		Category: "Daily Workflow",
		CastFile: "git-commit.cast",
	},
	{
		Name:     "git log",
		Cmd:      "git log — view history",
		Desc:     "Show the commit history of the repository",
		Category: "Daily Workflow",
		CastFile: "git-log.cast",
	},
	{
		Name:     "git diff",
		Cmd:      "git diff — compare changes",
		Desc:     "Show what changed in your working directory or between commits",
		Category: "Daily Workflow",
		CastFile: "git-diff.cast",
	},
	{
		Name:     "git reset",
		Cmd:      "git reset — unstage files",
		Desc:     "Remove files from the staging area without deleting them",
		Category: "Daily Workflow",
		CastFile: "git-reset.cast",
	},
	{
		Name:     "git branch",
		Cmd:      "git branch — manage branches",
		Desc:     "List, create, or delete branches",
		Category: "Branching",
		CastFile: "git-branch.cast",
	},
	{
		Name:     "git checkout",
		Cmd:      "git checkout — switch branches",
		Desc:     "Switch to a different branch or restore files",
		Category: "Branching",
		CastFile: "git-checkout.cast",
	},
	{
		Name:     "git merge",
		Cmd:      "git merge — combine branches",
		Desc:     "Merge another branch into your current branch",
		Category: "Branching",
		CastFile: "git-merge.cast",
	},
	{
		Name:     "git clone",
		Cmd:      "git clone — copy repository",
		Desc:     "Download a remote repository to your local machine",
		Category: "Remote",
		CastFile: "git-clone.cast",
	},
	{
		Name:     "git push",
		Cmd:      "git push — upload commits",
		Desc:     "Send your local commits to a remote repository",
		Category: "Remote",
		CastFile: "git-push.cast",
	},
	{
		Name:     "git pull",
		Cmd:      "git pull — download updates",
		Desc:     "Fetch and merge changes from a remote repository",
		Category: "Remote",
		CastFile: "git-pull.cast",
	},
	{
		Name:     "git revert",
		Cmd:      "git revert — undo a commit",
		Desc:     "Create a new commit that reverses a previous one",
		Category: "Undoing Changes",
		CastFile: "git-revert.cast",
	},
}
