package guide

// ZotEntries is the full list of zot guide items.
var ZotEntries = []Entry{
	{
		Name:     "zot setup",
		Cmd:      "zot setup — configure credentials",
		Desc:     "Save your Zotero API key, library ID, and data directory",
		Category: "Getting Started",
		CastFile: "zot-setup.cast",
	},
	{
		Name:     "zot info",
		Cmd:      "zot info — library summary",
		Desc:     "Show item counts, coverage, and type breakdown for your library",
		Category: "Getting Started",
		CastFile: "zot-info.cast",
	},
	{
		Name:     "zot search",
		Cmd:      "zot search — find items",
		Desc:     "Cross-field search by title, DOI, or publication",
		Category: "Browsing",
		CastFile: "zot-search.cast",
	},
	{
		Name:     "zot item list",
		Cmd:      "zot item list — browse items",
		Desc:     "List items with filters for type, collection, tag, and order",
		Category: "Browsing",
		CastFile: "zot-item-list.cast",
	},
	{
		Name:     "zot item read",
		Cmd:      "zot item read — item details",
		Desc:     "Show full metadata, abstract, tags, and attachments for one item",
		Category: "Browsing",
		CastFile: "zot-item-read.cast",
	},
	{
		Name:     "zot item open",
		Cmd:      "zot item open — open PDF",
		Desc:     "Launch an item's attachment in the default viewer",
		Category: "Browsing",
		CastFile: "zot-item-open.cast",
	},
	{
		Name:     "zot item add",
		Cmd:      "zot item add — create item",
		Desc:     "Create a new Zotero item via the Web API",
		Category: "Writing",
		CastFile: "zot-item-add.cast",
	},
	{
		Name:     "zot item update",
		Cmd:      "zot item update — patch fields",
		Desc:     "Update one or more items in a single batched PATCH",
		Category: "Writing",
		CastFile: "zot-item-update.cast",
	},
	{
		Name:     "zot item delete",
		Cmd:      "zot item delete — move to trash",
		Desc:     "Trash an item after a y/N confirmation",
		Category: "Writing",
		CastFile: "zot-item-delete.cast",
	},
	{
		Name:     "zot item export",
		Cmd:      "zot item export — emit citation",
		Desc:     "Export a single item as BibTeX or CSL-JSON",
		Category: "Export",
		CastFile: "zot-item-export.cast",
	},
	{
		Name:     "zot export",
		Cmd:      "zot export — library export",
		Desc:     "Full-library BibTeX export with semantic cite-keys",
		Category: "Export",
		CastFile: "zot-export.cast",
	},
	{
		Name:     "zot collection list",
		Cmd:      "zot collection list — browse collections",
		Desc:     "List every collection with its item count",
		Category: "Organize",
		CastFile: "zot-collection-list.cast",
	},
	{
		Name:     "zot collection create",
		Cmd:      "zot collection create — new collection",
		Desc:     "Create a new collection via the Zotero Web API",
		Category: "Organize",
		CastFile: "zot-collection-create.cast",
	},
	{
		Name:     "zot tags list",
		Cmd:      "zot tags list — browse tags",
		Desc:     "List every tag in the library with usage counts",
		Category: "Organize",
		CastFile: "zot-tags-list.cast",
	},
	{
		Name:     "zot doctor",
		Cmd:      "zot doctor — library health",
		Desc:     "Run every hygiene check and print a one-line dashboard",
		Category: "Hygiene",
		CastFile: "zot-doctor.cast",
	},
	{
		Name:     "zot doctor invalid",
		Cmd:      "zot doctor invalid — bad field values",
		Desc:     "Scan for malformed DOI/ISBN/URL/date values",
		Category: "Hygiene",
		CastFile: "zot-doctor-invalid.cast",
	},
	{
		Name:     "zot doctor missing",
		Cmd:      "zot doctor missing — coverage gaps",
		Desc:     "Show per-field coverage bars and missing-field findings",
		Category: "Hygiene",
		CastFile: "zot-doctor-missing.cast",
	},
	{
		Name:     "zot doctor orphans",
		Cmd:      "zot doctor orphans — structural orphans",
		Desc:     "Find empty collections, standalone attachments/notes, unused tags",
		Category: "Hygiene",
		CastFile: "zot-doctor-orphans.cast",
	},
	{
		Name:     "zot doctor duplicates",
		Cmd:      "zot doctor duplicates — find dupes",
		Desc:     "Cluster duplicate items by DOI and title (fuzzy opt-in)",
		Category: "Hygiene",
		CastFile: "zot-doctor-duplicates.cast",
	},
	{
		Name:     "zot doctor citekeys",
		Cmd:      "zot doctor citekeys — validate keys",
		Desc:     "Grade stored cite-keys against the v2 spec (valid/non-canonical/invalid/collision)",
		Category: "Hygiene",
		CastFile: "zot-doctor-citekeys.cast",
	},
	{
		Name:     "zot doctor citekeys --fix",
		Cmd:      "zot doctor citekeys --fix — repair keys",
		Desc:     "Dry-run preview + --apply to write canonical keys via the Web API",
		Category: "Hygiene",
		CastFile: "zot-doctor-citekeys-fix.cast",
	},
}
